<a href="https://colab.research.google.com/github/Conscious-Mind/tensorflow-deep-learning-notes/blob/main/01_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concenpts of tensors using TensorFlow
More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Maninpulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself

# Intoduction to Tensors

In [74]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [75]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [76]:
# Check the number of dimensions of a tensor (ndim stands for number of dimentsion)
scalar.ndim

0

In [77]:
 # Create a Vector
 vector = tf.constant([10, 11])
 vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 11], dtype=int32)>

In [78]:
vector.ndim

1

In [79]:
# Create a matrix (has more than 1 dimenstion)
matrix= tf.constant([[11,8],
                    [7, 22]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  8],
       [ 7, 22]], dtype=int32)>

In [80]:
matrix.ndim

2

In [81]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [4., 5.]], dtype=tf.float16) # Specify data type

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 4.,  5.]], dtype=float16)>

In [82]:
# What's the number of dimension in another matrix
another_matrix.ndim

2

In [83]:
# Let's create a tensor

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [84]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.Varaible`

In [85]:
# Create the same tensor with tf.Varaible() as above

changeable_tensor = tf.Variable([10, 11])
unchangeable_tensor = tf.constant([10, 11])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 11], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 11], dtype=int32)>)

In [86]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 8

TypeError: ignored

In [ ]:
# How about we try .assign()

changeable_tensor[0].assign(8)

In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assing(9)

 ### Creating random tensors

 Random tensors are tensors of some arbitary size which contain random numbers


In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(4)  # set seed fro reproducibility

random_1 = random_1.normal(shape=(3, 2))
random_1

In [ ]:
random_2 = tf.random.Generator.from_seed(4)
random_2 = random_2.normal(shape=(3, 2))
random_2

In [ ]:
# are the above two tensors equal

random_1 == random_2

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 5],
                            [7, 9]])

# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled, seed=4)

In [ ]:
not_shuffled

### 🛠 **Exercise:** Read through TensorFlow documentation on random seed generation.
Practice writing 5 random tensors and shuffle them

In [ ]:
random_11 = tf.random.normal(shape=(3, 3))
random_11

In [ ]:
tf.random.shuffle(random_11)

In [ ]:
random_12 = tf.random.normal(shape=(3, 2), seed=11)
random_12

In [ ]:
tf.random.shuffle(random_12)

In [ ]:
tf.random.set_seed(99)
random_13 = tf.random.normal(shape=(3,2))
random_13

In [ ]:
tf.random.shuffle(random_13)

In [ ]:
tf.random.set_seed(9)
random_14 = tf.random.normal(shape=(3,2), seed=10)
random_14

In [ ]:
tf.random.shuffle(random_14, seed= 11)

In [ ]:
tf.random.set_seed(7)
random_15 = tf.random.normal(shape=(3,2), seed=10)
random_15
tf.random.shuffle(random_15, seed= 71)

### Other ways to make tensors

In [87]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [88]:
# Create a tensor of all zeroes
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = 

# X = tf.constant(some_matrix) # Capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector