<a href="https://colab.research.google.com/github/Conscious-Mind/tensorflow-deep-learning-notes/blob/main/01_tensorflow_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛠 Exercises

##1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [ ]:
import tensorflow as tf

In [ ]:
scalar_a = tf.constant(11)

In [ ]:
vector_a = tf.constant([12, 13]) 

In [ ]:
matrix_a = tf.constant([[15, 16],
                        [17,18]])

In [ ]:
tensor_a = tf.constant([[[21, 22, 23],
                         [24, 25, 26],
                         [27, 28, 29]]])

##2. Find the shape, rank and size of the tensors you created in 1.

In [16]:
def print_values(name_of_tensor):
  print(f"The tensor is : {name_of_tensor.numpy()}")
  print(f"Datatype of every element: {name_of_tensor.dtype}")
  print(f"Number of dimensions(rank): {name_of_tensor.ndim}")
  print(f"Shape of tensor: {name_of_tensor.shape}")
  print(f"Size of tensor: {tf.size(name_of_tensor).numpy()}")

In [17]:
print_values(scalar_a)

The tensor is : 11
Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 0
Shape of tensor: ()
Size of tensor: 1


In [18]:
print_values(vector_a)

The tensor is : [12 13]
Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 1
Shape of tensor: (2,)
Size of tensor: 2


In [19]:
print_values(matrix_a)

The tensor is : [[15 16]
 [17 18]]
Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 2
Shape of tensor: (2, 2)
Size of tensor: 4


In [20]:
print_values(tensor_a)

The tensor is : [[[21 22 23]
  [24 25 26]
  [27 28 29]]]
Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 3
Shape of tensor: (1, 3, 3)
Size of tensor: 9


## 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [25]:
tf.random.set_seed(47)
first_tensor = tf.random.uniform(shape=[50, 300], minval=0, maxval=1, seed=11)
second_tensor = tf.random.uniform(shape=[50, 300], minval=0, maxval=1, seed=12)

In [26]:
first_tensor, second_tensor

(<tf.Tensor: shape=(50, 300), dtype=float32, numpy=
 array([[0.20114136, 0.22116268, 0.03055823, ..., 0.6479955 , 0.24345875,
         0.55817306],
        [0.08203161, 0.91801786, 0.18279874, ..., 0.82339203, 0.7164252 ,
         0.6833383 ],
        [0.08142698, 0.47079968, 0.12099791, ..., 0.85748553, 0.11779356,
         0.8613566 ],
        ...,
        [0.3960414 , 0.07969427, 0.48562074, ..., 0.43517935, 0.747736  ,
         0.31693983],
        [0.15113425, 0.62690485, 0.8805834 , ..., 0.5633352 , 0.65710366,
         0.76615167],
        [0.3290094 , 0.147174  , 0.59196794, ..., 0.7819625 , 0.452762  ,
         0.20070887]], dtype=float32)>,
 <tf.Tensor: shape=(50, 300), dtype=float32, numpy=
 array([[0.5152817 , 0.5063466 , 0.4255557 , ..., 0.24335611, 0.7606361 ,
         0.10213459],
        [0.9413791 , 0.78918076, 0.6985786 , ..., 0.6030663 , 0.29711366,
         0.05451024],
        [0.27447534, 0.02475142, 0.5281733 , ..., 0.9312116 , 0.01547956,
         0.49723864],
 

## 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [28]:
tf.matmul(first_tensor, tf.reshape(second_tensor, shape=(300, 50)))

<tf.Tensor: shape=(50, 50), dtype=float32, numpy=
array([[72.467834, 72.796875, 74.23915 , ..., 75.80961 , 78.640396,
        73.099304],
       [71.958206, 69.0612  , 73.66878 , ..., 71.48905 , 72.50463 ,
        67.963455],
       [75.19321 , 72.49446 , 74.95793 , ..., 76.25321 , 79.935715,
        72.98065 ],
       ...,
       [70.70889 , 69.558235, 71.97703 , ..., 72.378555, 74.66792 ,
        70.31729 ],
       [77.708786, 73.83981 , 81.59365 , ..., 78.77956 , 79.79515 ,
        77.95198 ],
       [72.737274, 71.07864 , 72.29835 , ..., 73.45082 , 74.2505  ,
        70.37079 ]], dtype=float32)>

## 5. Multiply the two tensors you created in 3 using dot product.

In [29]:
tf.tensordot(first_tensor, tf.reshape(second_tensor, shape=(300, 50)), axes=1)

<tf.Tensor: shape=(50, 50), dtype=float32, numpy=
array([[72.467834, 72.796875, 74.23915 , ..., 75.80961 , 78.640396,
        73.099304],
       [71.958206, 69.0612  , 73.66878 , ..., 71.48905 , 72.50463 ,
        67.963455],
       [75.19321 , 72.49446 , 74.95793 , ..., 76.25321 , 79.935715,
        72.98065 ],
       ...,
       [70.70889 , 69.558235, 71.97703 , ..., 72.378555, 74.66792 ,
        70.31729 ],
       [77.708786, 73.83981 , 81.59365 , ..., 78.77956 , 79.79515 ,
        77.95198 ],
       [72.737274, 71.07864 , 72.29835 , ..., 73.45082 , 74.2505  ,
        70.37079 ]], dtype=float32)>

## 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [30]:
tf.random.set_seed(51)
random_tensor = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1, seed=13)

In [31]:
random_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.04156268, 0.3480116 , 0.8167057 ],
        [0.24721384, 0.98169184, 0.35626018],
        [0.64160633, 0.75865674, 0.7032962 ],
        ...,
        [0.03502715, 0.99893713, 0.42883444],
        [0.229334  , 0.09627306, 0.31313884],
        [0.4846021 , 0.19260979, 0.7629881 ]],

       [[0.7917433 , 0.41008782, 0.39916193],
        [0.3082255 , 0.75269496, 0.02768266],
        [0.596498  , 0.637604  , 0.8569704 ],
        ...,
        [0.40223408, 0.53820646, 0.45503747],
        [0.24374235, 0.11702514, 0.7617402 ],
        [0.6250464 , 0.26121604, 0.57877254]],

       [[0.25713062, 0.577261  , 0.6770421 ],
        [0.10421407, 0.73274314, 0.96052647],
        [0.18635452, 0.7441082 , 0.73379564],
        ...,
        [0.87550974, 0.10845113, 0.53153265],
        [0.5900421 , 0.6527778 , 0.23440838],
        [0.4232334 , 0.7086215 , 0.5221095 ]],

       ...,

       [[0.00545514, 0.98632884, 0.0883528 ],
        [0.84

## 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [32]:
print(f"The maximum value of the tensor is: {tf.reduce_max(random_tensor)}")
print(f"The minimum value of the tensor is: {tf.reduce_min(random_tensor)}")

The maximum value of the tensor is: 0.9999994039535522
The minimum value of the tensor is: 6.4373016357421875e-06


## 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [33]:
tf.random.set_seed(52)
random2_tensor = tf.random.uniform(shape=[1, 224, 224, 3], seed= 52)

In [34]:
random2_tensor

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.68165016, 0.82013154, 0.7818153 ],
         [0.34372973, 0.14605904, 0.00669849],
         [0.9987531 , 0.10300064, 0.5306015 ],
         ...,
         [0.32794833, 0.7119155 , 0.67597353],
         [0.51198244, 0.16494977, 0.15637457],
         [0.3547585 , 0.7891878 , 0.03853965]],

        [[0.13987875, 0.78103673, 0.9334531 ],
         [0.0314635 , 0.30832338, 0.45488298],
         [0.4928398 , 0.21512175, 0.50047505],
         ...,
         [0.05172551, 0.21787763, 0.5016961 ],
         [0.19670379, 0.02885377, 0.54004276],
         [0.68002   , 0.7201747 , 0.14854395]],

        [[0.9660691 , 0.919405  , 0.7854806 ],
         [0.25211668, 0.07523513, 0.3744831 ],
         [0.34071004, 0.0494523 , 0.7524533 ],
         ...,
         [0.6395328 , 0.5334829 , 0.77524614],
         [0.04904115, 0.03726959, 0.69559   ],
         [0.9525478 , 0.65405655, 0.17827833]],

        ...,

        [[0.19358313, 0.60503006, 

In [35]:
random2_tensor.shape

TensorShape([1, 224, 224, 3])

In [36]:
random2_squeezed = tf.squeeze(random2_tensor)
random2_squeezed

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.68165016, 0.82013154, 0.7818153 ],
        [0.34372973, 0.14605904, 0.00669849],
        [0.9987531 , 0.10300064, 0.5306015 ],
        ...,
        [0.32794833, 0.7119155 , 0.67597353],
        [0.51198244, 0.16494977, 0.15637457],
        [0.3547585 , 0.7891878 , 0.03853965]],

       [[0.13987875, 0.78103673, 0.9334531 ],
        [0.0314635 , 0.30832338, 0.45488298],
        [0.4928398 , 0.21512175, 0.50047505],
        ...,
        [0.05172551, 0.21787763, 0.5016961 ],
        [0.19670379, 0.02885377, 0.54004276],
        [0.68002   , 0.7201747 , 0.14854395]],

       [[0.9660691 , 0.919405  , 0.7854806 ],
        [0.25211668, 0.07523513, 0.3744831 ],
        [0.34071004, 0.0494523 , 0.7524533 ],
        ...,
        [0.6395328 , 0.5334829 , 0.77524614],
        [0.04904115, 0.03726959, 0.69559   ],
        [0.9525478 , 0.65405655, 0.17827833]],

       ...,

       [[0.19358313, 0.60503006, 0.40408015],
        [0.10

In [37]:
random2_squeezed.shape

TensorShape([224, 224, 3])

## 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [39]:
tensor_10 = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

In [40]:
tensor_10, tensor_10.shape

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29], dtype=int32)>,
 TensorShape([10]))

In [42]:
print(f"The maximum value index: {tf.argmax(tensor_10)}\nThe maximum value: {tensor_10[tf.argmax(tensor_10)]}")

The maximum value index: 9
The maximum value: 29


In [43]:
print(f"The minimum value index: {tf.argmin(tensor_10)}\nThe minimum value: {tensor_10[tf.argmin(tensor_10)]}")

The minimum value index: 0
The minimum value: 2
