<a href="https://colab.research.google.com/github/Conscious-Mind/tensorflow-deep-learning-notes/blob/main/01_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concenpts of tensors using TensorFlow
More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Maninpulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself

# Intoduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimentsion)
scalar.ndim

0

In [5]:
 # Create a Vector
 vector = tf.constant([10, 11])
 vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 11], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
# Create a matrix (has more than 1 dimenstion)
matrix= tf.constant([[11,8],
                    [7, 22]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  8],
       [ 7, 22]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [4., 5.]], dtype=tf.float16) # Specify data type

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 4.,  5.]], dtype=float16)>

In [10]:
# What's the number of dimension in another matrix
another_matrix.ndim

2

In [11]:
# Let's create a tensor

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.Varaible`

In [13]:
# Create the same tensor with tf.Varaible() as above

changeable_tensor = tf.Variable([10, 11])
unchangeable_tensor = tf.constant([10, 11])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 11], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 11], dtype=int32)>)

In [14]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 8

TypeError: ignored

In [15]:
# How about we try .assign()

changeable_tensor[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 8, 11], dtype=int32)>

In [16]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assing(9)

AttributeError: ignored

 ### Creating random tensors

 Random tensors are tensors of some arbitary size which contain random numbers


In [22]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(4)  # set seed fro reproducibility

random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0019137 ,  0.6735137 ],
       [ 0.06987712, -1.4077919 ],
       [ 1.0278524 ,  0.27974114]], dtype=float32)>

In [24]:
random_2 = tf.random.Generator.from_seed(4)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0019137 ,  0.6735137 ],
       [ 0.06987712, -1.4077919 ],
       [ 1.0278524 ,  0.27974114]], dtype=float32)>

In [25]:
# are the above two tensors equal

random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>