<a href="https://colab.research.google.com/github/Conscious-Mind/tensorflow-deep-learning-notes/blob/main/01_tensorflow_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛠 Exercises

##1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [ ]:
import tensorflow as tf

In [ ]:
scalar_a = tf.constant(11)

In [ ]:
vector_a = tf.constant([12, 13]) 

In [ ]:
matrix_a = tf.constant([[15, 16],
                        [17,18]])

In [ ]:
tensor_a = tf.constant([[[21, 22, 23],
                         [24, 25, 26],
                         [27, 28, 29]]])

##2. Find the shape, rank and size of the tensors you created in 1.

In [16]:
def print_values(name_of_tensor):
  print(f"The tensor is : {name_of_tensor.numpy()}")
  print(f"Datatype of every element: {name_of_tensor.dtype}")
  print(f"Number of dimensions(rank): {name_of_tensor.ndim}")
  print(f"Shape of tensor: {name_of_tensor.shape}")
  print(f"Size of tensor: {tf.size(name_of_tensor).numpy()}")

In [17]:
print_values(scalar_a)

The tensor is : 11
Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 0
Shape of tensor: ()
Size of tensor: 1


In [18]:
print_values(vector_a)

The tensor is : [12 13]
Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 1
Shape of tensor: (2,)
Size of tensor: 2


In [19]:
print_values(matrix_a)

The tensor is : [[15 16]
 [17 18]]
Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 2
Shape of tensor: (2, 2)
Size of tensor: 4


In [20]:
print_values(tensor_a)

The tensor is : [[[21 22 23]
  [24 25 26]
  [27 28 29]]]
Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 3
Shape of tensor: (1, 3, 3)
Size of tensor: 9


## 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [25]:
tf.random.set_seed(47)
first_tensor = tf.random.uniform(shape=[50, 300], minval=0, maxval=1, seed=11)
second_tensor = tf.random.uniform(shape=[50, 300], minval=0, maxval=1, seed=12)

In [26]:
first_tensor, second_tensor

(<tf.Tensor: shape=(50, 300), dtype=float32, numpy=
 array([[0.20114136, 0.22116268, 0.03055823, ..., 0.6479955 , 0.24345875,
         0.55817306],
        [0.08203161, 0.91801786, 0.18279874, ..., 0.82339203, 0.7164252 ,
         0.6833383 ],
        [0.08142698, 0.47079968, 0.12099791, ..., 0.85748553, 0.11779356,
         0.8613566 ],
        ...,
        [0.3960414 , 0.07969427, 0.48562074, ..., 0.43517935, 0.747736  ,
         0.31693983],
        [0.15113425, 0.62690485, 0.8805834 , ..., 0.5633352 , 0.65710366,
         0.76615167],
        [0.3290094 , 0.147174  , 0.59196794, ..., 0.7819625 , 0.452762  ,
         0.20070887]], dtype=float32)>,
 <tf.Tensor: shape=(50, 300), dtype=float32, numpy=
 array([[0.5152817 , 0.5063466 , 0.4255557 , ..., 0.24335611, 0.7606361 ,
         0.10213459],
        [0.9413791 , 0.78918076, 0.6985786 , ..., 0.6030663 , 0.29711366,
         0.05451024],
        [0.27447534, 0.02475142, 0.5281733 , ..., 0.9312116 , 0.01547956,
         0.49723864],
 

## 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [28]:
tf.matmul(first_tensor, tf.reshape(second_tensor, shape=(300, 50)))

<tf.Tensor: shape=(50, 50), dtype=float32, numpy=
array([[72.467834, 72.796875, 74.23915 , ..., 75.80961 , 78.640396,
        73.099304],
       [71.958206, 69.0612  , 73.66878 , ..., 71.48905 , 72.50463 ,
        67.963455],
       [75.19321 , 72.49446 , 74.95793 , ..., 76.25321 , 79.935715,
        72.98065 ],
       ...,
       [70.70889 , 69.558235, 71.97703 , ..., 72.378555, 74.66792 ,
        70.31729 ],
       [77.708786, 73.83981 , 81.59365 , ..., 78.77956 , 79.79515 ,
        77.95198 ],
       [72.737274, 71.07864 , 72.29835 , ..., 73.45082 , 74.2505  ,
        70.37079 ]], dtype=float32)>

## 5. Multiply the two tensors you created in 3 using dot product.

In [29]:
tf.tensordot(first_tensor, tf.reshape(second_tensor, shape=(300, 50)), axes=1)

<tf.Tensor: shape=(50, 50), dtype=float32, numpy=
array([[72.467834, 72.796875, 74.23915 , ..., 75.80961 , 78.640396,
        73.099304],
       [71.958206, 69.0612  , 73.66878 , ..., 71.48905 , 72.50463 ,
        67.963455],
       [75.19321 , 72.49446 , 74.95793 , ..., 76.25321 , 79.935715,
        72.98065 ],
       ...,
       [70.70889 , 69.558235, 71.97703 , ..., 72.378555, 74.66792 ,
        70.31729 ],
       [77.708786, 73.83981 , 81.59365 , ..., 78.77956 , 79.79515 ,
        77.95198 ],
       [72.737274, 71.07864 , 72.29835 , ..., 73.45082 , 74.2505  ,
        70.37079 ]], dtype=float32)>