<a href="https://colab.research.google.com/github/Conscious-Mind/tensorflow-deep-learning-notes/blob/main/01_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concenpts of tensors using TensorFlow
More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Maninpulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself

# Intoduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimentsion)
scalar.ndim

0

In [4]:
 # Create a Vector
 vector = tf.constant([10, 11])
 vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 11], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimenstion)
matrix= tf.constant([[11,8],
                    [7, 22]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  8],
       [ 7, 22]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [4., 5.]], dtype=tf.float16) # Specify data type

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 4.,  5.]], dtype=float16)>

In [9]:
# What's the number of dimension in another matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.Varaible`

In [12]:
# Create the same tensor with tf.Varaible() as above

changeable_tensor = tf.Variable([10, 11])
unchangeable_tensor = tf.constant([10, 11])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 11], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 11], dtype=int32)>)

In [14]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 8

TypeError: ignored

In [15]:
# How about we try .assign()

changeable_tensor[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 8, 11], dtype=int32)>

In [16]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assing(9)

AttributeError: ignored

 ### Creating random tensors

 Random tensors are tensors of some arbitary size which contain random numbers


In [17]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(4)  # set seed fro reproducibility

random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0019137 ,  0.6735137 ],
       [ 0.06987712, -1.4077919 ],
       [ 1.0278524 ,  0.27974114]], dtype=float32)>

In [18]:
random_2 = tf.random.Generator.from_seed(4)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0019137 ,  0.6735137 ],
       [ 0.06987712, -1.4077919 ],
       [ 1.0278524 ,  0.27974114]], dtype=float32)>

In [19]:
# are the above two tensors equal

random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a tensor

In [20]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 5],
                            [7, 9]])

# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  5],
       [10,  7],
       [ 7,  9]], dtype=int32)>

In [21]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled, seed=4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7,  9],
       [ 3,  5]], dtype=int32)>

In [22]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 7,  9]], dtype=int32)>

### 🛠 **Exercise:** Read through TensorFlow documentation on random seed generation.
Practice writing 5 random tensors and shuffle them

In [23]:
random_11 = tf.random.normal(shape=(3, 3))
random_11

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.5983449 ,  0.06276207,  0.14631742],
       [ 0.48481876, -0.23572342,  0.61806035],
       [-0.30146384,  1.1635462 ,  0.59415627]], dtype=float32)>

In [24]:
tf.random.shuffle(random_11)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.48481876, -0.23572342,  0.61806035],
       [ 0.5983449 ,  0.06276207,  0.14631742],
       [-0.30146384,  1.1635462 ,  0.59415627]], dtype=float32)>

In [25]:
random_12 = tf.random.normal(shape=(3, 2), seed=11)
random_12

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.6056037 ,  2.2249544 ],
       [-0.53603446, -0.9164999 ],
       [ 1.2182597 , -0.20914607]], dtype=float32)>

In [26]:
tf.random.shuffle(random_12)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.6056037 ,  2.2249544 ],
       [-0.53603446, -0.9164999 ],
       [ 1.2182597 , -0.20914607]], dtype=float32)>

In [27]:
tf.random.set_seed(99)
random_13 = tf.random.normal(shape=(3,2))
random_13

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.39410433, -0.43982184],
       [ 0.51258147,  0.21715854],
       [-0.55385107,  2.5249932 ]], dtype=float32)>

In [28]:
tf.random.shuffle(random_13)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.39410433, -0.43982184],
       [ 0.51258147,  0.21715854],
       [-0.55385107,  2.5249932 ]], dtype=float32)>

In [29]:
tf.random.set_seed(9)
random_14 = tf.random.normal(shape=(3,2), seed=10)
random_14

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.5047617 ,  0.6216561 ],
       [ 3.0548055 ,  0.32961133],
       [-0.46231833, -0.94684684]], dtype=float32)>

In [30]:
tf.random.shuffle(random_14, seed= 11)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.5047617 ,  0.6216561 ],
       [-0.46231833, -0.94684684],
       [ 3.0548055 ,  0.32961133]], dtype=float32)>

In [31]:
tf.random.set_seed(7)
random_15 = tf.random.normal(shape=(3,2), seed=10)
random_15
tf.random.shuffle(random_15, seed= 71)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.95489764, -0.21685009],
       [ 0.5349388 ,  2.625628  ],
       [-0.0164918 ,  1.1715828 ]], dtype=float32)>

### Other ways to make tensors

In [32]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [33]:
# Create a tensor of all zeroes
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [34]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array bt 1 & 25
numpy_A

# X = tf.constant(some_matrix) # Capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [35]:
A = tf.constant(numpy_A, shape=(2,2,2,3))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
 array([[[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [10, 11, 12]]],
 
 
        [[[13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24]]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Getting information from tensors


### When deating with tensors you probably want to be aware of the following attributes

* Shape  `tensor.shape`
* Rank   `tensor.ndim`
* Axis or dimension   `tensor[0], tensor[:,1*]...`*
* Size   `tf.size(tensor)`

In [36]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [38]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor))
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): tf.Tensor(120, shape=(), dtype=int32)
Total number of elements (2*3*4*5): 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [39]:
some_list = [1, 2, 3, 4]
some_list[:3]

[1, 2, 3]

In [40]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [41]:
some_list[:1]

[1]

In [42]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [43]:
# Get each first elment from each dimension from index except for the final line
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [44]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[4, 7],
                 [5, 2]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [45]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 7],
       [5, 2]], dtype=int32)>

In [46]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 2], dtype=int32)>

In [47]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[4],
        [7]],

       [[5],
        [2]]], dtype=int32)>

In [48]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # axis=-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[4],
        [7]],

       [[5],
        [2]]], dtype=int32)>

In [49]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=0) # axis=0 means expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[4, 7],
        [5, 2]]], dtype=int32)>

In [50]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 7],
       [5, 2]], dtype=int32)>

### Manipulating tensors(tensor operation)



####**Basic operations**

`+`,`-`,`*`,`/`

* `tf.math.add`
* `tf.math.subtract`
* `tf.math.multiply`
* `tf.math.divide`

In [51]:
# You can add value to  a tensor using the addition operatior

tensor = tf.constant([[10, 11],
                      [12, 13]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 21],
       [22, 23]], dtype=int32)>

In [52]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 11],
       [12, 13]], dtype=int32)>

In [53]:
# Multiplication
tensor * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 33],
       [36, 39]], dtype=int32)>

In [54]:
#Subtraction

tensor - 12

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-2, -1],
       [ 0,  1]], dtype=int32)>

In [55]:
# Division
tensor / 3

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3.33333333, 3.66666667],
       [4.        , 4.33333333]])>

In [56]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 12)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 132],
       [144, 156]], dtype=int32)>

In [57]:
tensor # still unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 11],
       [12, 13]], dtype=int32)>

####**Matrix Multiplication**

In machine learning, matrix multiplication is one of the most common tensor operation

You can matrix multipy using

* `tf.matmul(x, y)`
* `tf.tensordot(x, y, axes)`

In [58]:
# Matrix Multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10 11]
 [12 13]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[232, 253],
       [276, 301]], dtype=int32)>

In [59]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 121],
       [144, 169]], dtype=int32)>

In [60]:
# Matrix Multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[232, 253],
       [276, 301]], dtype=int32)>

In [61]:
# Create a tensor (3, 2) tensor
X = tf.constant([[1, 2],
                 [3,4],
                 [5, 6]])
# Create another (3, 2 ) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [62]:
# Try to matrix mult tensors of same shape
X @ Y

InvalidArgumentError: ignored

In [ ]:
Y

In [ ]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2,3))

In [ ]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

In [ ]:
# Changing the shape of X instead of Y to matrix multiply
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

In [63]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

####Changing the datatype of tensor

In [64]:
tf.__version__

'2.7.0'

In [65]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 3.3])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 3.3], dtype=float32)>

In [66]:
# Create aother tensor with default datatype (int32)
C = tf.constant([4, 6])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [67]:
# change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 3.3], dtype=float16)>

In [68]:
# Change from int32 to int16
E = tf.cast(C, dtype=tf.int16)
E

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([4, 6], dtype=int16)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to smaller amount of values

In [69]:
# Get the absolute values
F = tf.constant([-5, -8])
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-5, -8], dtype=int32)>

In [70]:
# Get absolute value
tf.abs(F)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 8], dtype=int32)>

Let's go through the following forms of aggreation:

* Get the minimun
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [71]:
import numpy as np

In [72]:
# Create a random tensor with values between 0 and 100 of size 50

G = tf.constant(np.random.randint(0, 100, size= 50))
G

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([24, 31, 76,  5, 47, 77, 29, 24, 21, 27,  0, 28, 19, 55, 11,  3, 16,
       21, 26, 94, 20, 44, 81, 58,  1, 38, 96, 50, 13, 70, 91, 38, 68,  2,
        3, 15, 43, 85, 81,  9, 72, 40, 31, 20, 84, 42, 40, 95,  3, 24])>

In [73]:
tf.size(G), G.shape, G.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [74]:
# Find the minimum
tf.reduce_min(G)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [75]:
np.min(G)

0

In [76]:
# Find the maximum
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [77]:
np.max(G)

96

In [78]:
#Find the mean
tf.reduce_mean(G)

<tf.Tensor: shape=(), dtype=int64, numpy=39>

In [79]:
np.mean(G)

39.82

In [80]:
#Find the sum
tf.reduce_sum(G)

<tf.Tensor: shape=(), dtype=int64, numpy=1991>

In [81]:
np.sum(G)

1991

In [82]:
# Find the variance of our tensor, we need not access to tensorflow_probability
import tensorflow_probability as tfp

tfp.stats.variance(G)

<tf.Tensor: shape=(), dtype=int64, numpy=845>

In [83]:
# Find the variance of our tensor
tf.math.reduce_variance(tf.cast(G, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=845.1877>

In [84]:
# Find the Standard Deviation of our tensor
tf.math.reduce_std(tf.cast(G, dtype=tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=29.072111>

###**Find the positional maximum and minimum**

In [85]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
H = tf.random.uniform(shape=[50])
H

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [86]:
# Find the positional maximum
tf.argmax(H)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [87]:
# Index on our largest value position
H[tf.argmax(H)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [88]:
# Find the max value of H
tf.reduce_max(H)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [89]:
# Check for equlaity
H[tf.argmax(H)] == tf.reduce_max(H)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [90]:
# Find the positional minimum
tf.argmin(H)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [91]:
# Index on our largest value position
H[tf.argmin(H)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [92]:
# Find the max value of H
tf.reduce_min(H)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [93]:
# Check for equlaity
H[tf.argmin(H)] == tf.reduce_min(H)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [94]:
# Create a tensor to get started
tf.random.set_seed(42)
I = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
I

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [95]:
I.shape

TensorShape([1, 1, 1, 1, 50])

In [96]:
I_squeezed = tf.squeeze(I)
I_squeezed, I_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors

In [97]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [98]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="ON", off_value="OFF")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

###Some other common mathematical operation

* Squaring
* Squre root
* Log

In [99]:
# Create a new tensor
J = tf.range(1, 10)
J

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [100]:
# Squaring J
tf.square(J)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [101]:
# Square root of J
tf.sqrt(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [102]:
# Log of J
tf.math.log(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors & NumPy

TensorFlow interacts beautifully with NumPy arrays

In [103]:
# Create a tensor directly from a NumPy array
I = tf.constant(np.array([3., 7., 10.]))
I

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [104]:
# Convert our tensor back to a NumPy array
np.array(I), type(np.array(I))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [105]:
# Convert tenor to NumPy array
I.numpy(), type(I.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [106]:
# The default types of each are slightly different
numpy_I = tf.constant(np.array([3., 7., 10.]))
tensor_I = tf.constant([3., 7., 10.])


In [107]:
# Check the datatype of each above
numpy_I.dtype, tensor_I.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [108]:
import tensorflow as tf

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [109]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found
